#!/usr/bin/env node
'use strict';

// BG WH \u001b[47m
// BOLD  \u001b[1m
// RED   \u001b[31m
// GREEN \u001b[32m
// RESET \u001b[0m

[ '',
  '\u001b[31m===============================\u001b[0m',
  '\u001b[31m==\u001b[0m Do you rely on Greenlock? \u001b[31m==\u001b[0m',
  '\u001b[31m===============================\u001b[0m',
  '',
  "Hey! Let's Encrypt will \u001b[31mSTOP WORKING\u001b[0m with Greenlock v2 at the end of October,",
  "and \u001b[31mWITHOUT YOUR HELP\u001b[0m we won't get the next release out in time.",
  '',
  "If Greenlock has saved you time and money, and taken stress out of your life,",
  "or you just love it, please reach out to return the favor today:",
  '',
  '\u001b[31mSAVE GREENLOCK:\u001b[0m',
  'https://indiegogo.com/at/greenlock',
  ''
].forEach(function (line) {
  console.info(line);
});
